#!/bin/bash

## Open links in browser
FILE="$HOME/.cache/eww_launch.dashboard"
CFG="$HOME/.config/eww/dashboard"
EWW=`which eww`
cmd="firefox --new-tab"
brave_cmd="brave --new-window"
brave_tab_cmd="brave --new-tab"

close_dash() {
	${EWW} --config "$CFG" close \
					background profile system clock music github \
					reddit twitter youtube weather hackernews logout sleep reboot poweroff folders
	rm -rf "$FILE"
}

if [[ "$1" == "--gh" ]]; then
	close_dash && ${cmd} "https://github.com"

elif [[ "$1" == "--work" ]]; then
	close_dash && ${brave_cmd}

elif [[ "$1" == "--gmail" ]]; then
	close_dash && ${brave_tab_cmd} "https://mail.google.com/mail/u/0/#inbox"

elif [[ "$1" == "--rd" ]]; then
	close_dash && ${cmd} "https://reddit.com"

elif [[ "$1" == "--tw" ]]; then
	close_dash && ${brave_tab_cmd} "https://x.com"

elif [[ "$1" == "--yt" ]]; then
	close_dash && ${brave_tab_cmd} "https://youtube.com"

fi
